homeassistant:
  name: !secret ha_name
  latitude: !secret ha_lat
  longitude: !secret ha_lon
  elevation: !secret ha_el
  unit_system: metric
  time_zone: Europe/London
  customize: !include_dir_merge_named customize
#  customize_glob: !include ui/ui.yaml

#customizer:
#  custom_ui: local

frontend: !include frontend/frontend.yaml
config:
updater:
conversation:
history:
sun:
ios:
upnp: !include platform/upnp.yaml
logbook: !include logbook/logbook.yaml
discovery: !include discovery/discovery.yaml
zeroconf:
map:

ffmpeg: !include platform/ffmpeg.yaml
recorder: !include recorder/recorder.yaml
http: !include platform/http.yaml
netatmo: !include platform/netatmo.yaml
ring: !include platform/ring.yaml
tts: !include platform/tts.yaml
binary_sensor: !include_dir_merge_list binary_sensor
sensor: !include_dir_merge_list sensor
media_player: !include_dir_merge_list mediaplayer
device_tracker: !include_dir_merge_list device_tracker
camera: !include_dir_merge_list camera
light: !include_dir_merge_list light
automation: !include_dir_merge_list automation
notify: !include_dir_merge_list notify
switch: !include_dir_merge_list switch
group: !include_dir_merge_named group
zwave: !include platform/zwave.yaml
input_select: !include_dir_merge_named input
shell_command: !include_dir_merge_named shell
panel_custom: !include_dir_merge_list panel_custom
panel_iframe: !include_dir_merge_named panel_iframe
scene: !include_dir_merge_list scenes
logger: !include logger/logger.yaml
apple_tv: !include apple_tv/lounge.yaml
mqtt: !include mqtt/mqtt.yaml
zone:  !include zones/zone_alex_work.yaml
zone 2:  !include zones/zone_rebecca_work.yaml
script: !include_dir_merge_named script
emulated_hue: !include platform/emulated_hue.yaml

input_number: !include_dir_merge_named input_number
input_boolean: !include_dir_merge_named input_boolean
