- alias: 'Chester Motion Started'
  trigger:
    platform: state
    entity_id: sensor.chester_motion
    from: 'No Motion'
    to: 'Motion'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: device_tracker.alex
        state: not_home
      - condition: state
        entity_id: device_tracker.rebecca
        state: not_home
  action:
    service: notify.alex_notify
    data:
      message: "There is motion in the Chester's Room"

- alias: 'Chester Motion Ended'
  trigger:
    platform: state
    entity_id: sensor.chester_motion
    from: 'Motion'
    to: 'No Motion'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: device_tracker.alex
        state: not_home
      - condition: state
        entity_id: device_tracker.rebecca
        state: not_home
  action:
    service: notify.alex_notify
    data:
      message: "There is no motion in the Chester's Room"