- alias: 'Kitchen Motion Started'
  trigger:
    platform: state
    entity_id: sensor.aeotec_zw100_multisensor_6_burglar_2
    from: '0'
    to: '8'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: device_tracker.alex
        state: not_home
      - condition: state
        entity_id: device_tracker.rebecca
        state: not_home
  action:
    service: notify.slack
    data:
      message: "Motion detected in the kitchen"

- alias: 'Kitchen Motion Ended'
  trigger:
    platform: state
    entity_id: sensor.aeotec_zw100_multisensor_6_burglar_2
    from: '8'
    to: '0'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: device_tracker.alex
        state: not_home
      - condition: state
        entity_id: device_tracker.rebecca
        state: not_home
  action:
    service: notify.slack
    data:
      message: "No Motion detected in the kitchen"